name: Release
on:
  push:
    branches: [ $default-branch ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: "@open-universities-australia"
        env:
          # We need to use a PAT with READ access to packages inside the organisation to install any dependencies.
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGE_READ_ONLY }}
      - name: Install dependencies
        run: npm ci
      - name: Build Package
        run: npm run build
      - name: Release
        env:
          # We use the default GITHUB_TOKEN to publish the artifact.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release